const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSSAGE = "NEW_MESSSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSSAGE,
  START_TYPING,
  STOP_TYPING,
};
